### ISSUE TITLE
RuntimeError: CUDA error (10): invalid device ordinal (check_status at /pytorch/aten/src/ATen/cuda/detail/CUDAHooks.cpp:36)

### ISSUE THREAD

**Issue by pandazha** [princeton-vl/CornerNet#15]
when I train CornerNet, RuntimeError: CUDA error (10): invalid device ordinal (check_status at /pytorch/aten/src/ATen/cuda/detail/CUDAHooks.cpp:36) how to solver this problem

**Comment by heilaw** [comment]
According to [this](https://github.com/torch/cutorch/issues/503#issuecomment-250769334), "invalid device ordinal" means the program cannot access your GPU(s). You can check if your GPU(s) are being detected correctly using the following Python code:

```
import torch
torch.cuda.is_available()
```

If it returns `False`, that means PyTorch cannot detect your GPU(s). You may want to reinstall PyTorch to see if that helps. If it returns `True`, can you post the error with stack trace?

**Comment by pandazha** [comment]
it returns True   torch.cuda.device_count() returns 8

 stack trace：
  0%|                                                | 0/500000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/zhangfengdong/pycharm-2017.3/helpers/pydev/pydevd.py", line 1683, in <module>
    main()
  File "/data/zhangfengdong/pycharm-2017.3/helpers/pydev/pydevd.py", line 1677, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/data/zhangfengdong/pycharm-2017.3/helpers/pydev/pydevd.py", line 1087, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/zhangfengdong/pycharm-2017.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/zhangfengdong/CornerNet-master/train.py", line 195, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "/data/zhangfengdong/CornerNet-master/train.py", line 137, in train
    training_loss = nnet.train(**training)
  File "/data/zhangfengdong/CornerNet-master/nnet/py_factory.py", line 81, in train
    loss = self.network(xs, ys)
  File "/data/zhangfengdong/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/zhangfengdong/CornerNet-master/models/py_utils/data_parallel.py", line 66, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids, self.chunk_sizes)
  File "/data/zhangfengdong/CornerNet-master/models/py_utils/data_parallel.py", line 77, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim, chunk_sizes=self.chunk_sizes)
  File "/data/zhangfengdong/CornerNet-master/models/py_utils/scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim, chunk_sizes) if inputs else []
  File "/data/zhangfengdong/CornerNet-master/models/py_utils/scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "/data/zhangfengdong/CornerNet-master/models/py_utils/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/data/zhangfengdong/CornerNet-master/models/py_utils/scatter_gather.py", line 20, in scatter_map
    return list(map(list, zip(*map(scatter_map, obj))))
  File "/data/zhangfengdong/CornerNet-master/models/py_utils/scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, chunk_sizes, dim, obj)
  File "/data/zhangfengdong/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 87, in forward
    outputs = comm.scatter(input, ctx.target_gpus, ctx.chunk_sizes, ctx.dim, streams)
  File "/data/zhangfengdong/anaconda3/lib/python3.6/site-packages/torch/cuda/comm.py", line 142, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error (10): invalid device ordinal (check_status at /pytorch/aten/src/ATen/cuda/detail/CUDAHooks.cpp:36)

**Comment by heilaw** [comment]
I think you may want to try the following.

1. The default configuration file assumes that there are 10 GPUs and you only have 8 GPUs. Did you change the `batch_size` and `chunk_sizes` in `config/CornerNet.json` file? `chunk_sizes` means the number of images per GPU. If you haven't changed that, try reducing the batch size and adjust the `chunk_sizes` accordingly.

2. Reinstall CUDA/CUDNN/CONDA as suggested [here](https://discuss.pytorch.org/t/cuda-issue-cuda-runtime-error-10-invalid-device-ordinal/19551)

**Comment by pandazha** [comment]
Thank you for your answer，it works.

**Comment by flyindirt** [comment]
this works,  change the config "chunk_sizes": [5, 5] for 2 gpu.

> I think you may want to try the following.
> 
> 1. The default configuration file assumes that there are 10 GPUs and you only have 8 GPUs. Did you change the `batch_size` and `chunk_sizes` in `config/CornerNet.json` file? `chunk_sizes` means the number of images per GPU. If you haven't changed that, try reducing the batch size and adjust the `chunk_sizes` accordingly.

**Comment by czhi3** [comment]
> According to [this](https://github.com/torch/cutorch/issues/503#issuecomment-250769334), "invalid device ordinal" means the program cannot access your GPU(s). You can check if your GPU(s) are being detected correctly using the following Python code:
> 
> ```
> import torch
> torch.cuda.is_available()
> ```
> 
> If it returns `False`, that means PyTorch cannot detect your GPU(s). You may want to reinstall PyTorch to see if that helps. If it returns `True`, can you post the error with stack trace?

when I train CornerNet, RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:663  
Excuse me ! how should I solver this problem?

run True torch.cuda.device_count() returns 2
I try to change the batch_size：8 and chunk_sizes：[4,4]


Traceback (most recent call last):
  File "train.py", line 199, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "train.py", line 138, in train
    training_loss = nnet.train(**training)
  File "/home/cz/CornerNet-master/nnet/py_factory.py", line 81, in train
    loss = self.network(xs, ys)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cz/CornerNet-master/models/py_utils/data_parallel.py", line 70, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/cz/CornerNet-master/models/py_utils/data_parallel.py", line 80, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cz/CornerNet-master/nnet/py_factory.py", line 19, in forward
    preds = self.model(*xs, **kwargs)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cz/CornerNet-master/nnet/py_factory.py", line 31, in forward
    return self.module(*xs, **kwargs)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cz/CornerNet-master/models/py_utils/kp.py", line 253, in forward
    return self._train(*xs, **kwargs)
  File "/home/cz/CornerNet-master/models/py_utils/kp.py", line 171, in _train
    inter = self.pre(image)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cz/CornerNet-master/models/py_utils/utils.py", line 14, in forward
    conv = self.conv(x)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cz/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
