### ISSUE TITLE
IndexError: index 128 is out of bounds for axis 1 with size 128

### ISSUE THREAD

**Issue by XiaSunny** [princeton-vl/CornerNet#26]
When i train my own data , i meet this problem:

training loss at iteration 270: 8.091086387634277                               
training loss at iteration 275: 8.255900382995605                               
training loss at iteration 280: 8.269482612609863                               
training loss at iteration 285: 8.271137237548828                               
  3%|█                                    | 286/10000 [07:02<3:59:10,  1.48s/it]Traceback (most recent call last):
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/chase/application/CornerNet/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/chase/application/CornerNet/sample/coco.py", line 157, in kp_detection
    tl_regrs[b_ind, tag_ind, :] = [fxtl - xtl, fytl - ytl]
IndexError: index 128 is out of bounds for axis 1 with size 128
Process Process-2:
Traceback (most recent call last):
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 46, in prefetch_data
    raise e
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/chase/application/CornerNet/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/chase/application/CornerNet/sample/coco.py", line 157, in kp_detection
    tl_regrs[b_ind, tag_ind, :] = [fxtl - xtl, fytl - ytl]
IndexError: index 128 is out of bounds for axis 1 with size 128
  3%|█                                    | 287/10000 [07:03<3:59:08,  1.48s/it]Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 50, in pin_memory
    data = data_queue.get()
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/chase/anaconda2/envs/CornerNet/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

Thank  @heilaw

**Comment by heilaw** [comment]
I believe this error happens because there are more than 128 objects in your image. In order to parallelize the calculation of loss function, we made some assumption in the implementation and we assumed there are at most 128 objects in an image. You can adjust `max_tag_len` (line 66 in `sample/coco.py`) according to your dataset.

**Comment by XiaSunny** [comment]
It works. Thank you ! @heilaw
