### ISSUE TITLE
change the default input size, confronting with the size problem

### ISSUE THREAD

**Issue by djmirv** [princeton-vl/CornerNet#62]
I've experimented on my own dataset, but it converges at about 8 and doesn't go lower. So i try to modify the network with the input size from **511** to **415** in the files of **CornerNet.json** and **detection.py**, but met with this problem. While recovering to **511**, it runs successfull again). 
Any idea? Thx in advance.

```
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "train.py", line 137, in train
    training_loss = nnet.train(**training)
  File "/home/jim/CornerNet/nnet/py_factory.py", line 81, in train
    loss = self.network(xs, ys)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/data_parallel.py", line 68, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/nnet/py_factory.py", line 19, in forward
    preds = self.model(*xs, **kwargs)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/nnet/py_factory.py", line 31, in forward
    return self.module(*xs, **kwargs)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/kp.py", line 255, in forward
    return self._train(*xs, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/kp.py", line 190, in _train
    kp  = kp_(inter)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/kp.py", line 68, in forward
    low2 = self.low2(low1)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/kp.py", line 68, in forward
    low2 = self.low2(low1)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/kp.py", line 68, in forward
    low2 = self.low2(low1)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/kp.py", line 68, in forward
    low2 = self.low2(low1)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/kp.py", line 71, in forward
    return self.merge(up1, up2)
  File "/home/jim/.conda/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jim/CornerNet/models/py_utils/kp_utils.py", line 9, in forward
    return up1 + up2
RuntimeError: The size of tensor a (7) must match the size of tensor b (8) at non-singleton dimension 3
```

**Comment by JackJunle** [comment]
I think you should modify the structure of this Network, since the sizes of input and output of Hourglass in CornerNet are 128, which is from 511/4 ( A Convlayer and a ResBlock before Hourglass, both of them have strides=2) . When you change 511 to 415, it cannot get 128....

**Comment by djmirv** [comment]
Thank Jack. When I change both the output size and the input size as following, the error won't occur:
```
        "input_size": [256, 256],
        "output_sizes": [[64, 64]],
```
