### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by flyingfQiu** [princeton-vl/CornerNet#64]
Sorry to interrupt. I have encountered a RuntimeError, the detail is shown as follows. Could you offer me a help to solve it? Thank you!
The error happens on line _136_ in ‘train.py’
`training start...
  0%|                                                | 0/500000 [00:00<?, ?it/s]^CWe've got an error while stopping in post-mortem: <class 'RuntimeError'>
We've got an error while stopping in post-mortem: <class 'RuntimeError'>
We've got an error while stopping in post-mortem: <class 'RuntimeError'>
We've got an error while stopping in post-mortem: <class 'RuntimeError'>
We've got an error while stopping in post-mortem: <class 'RuntimeError'>
Traceback (most recent call last):
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/__main__.py", line 265, in main
    wait=args.wait)
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/__main__.py", line 258, in handle_args
    debug_main(addr, name, kind, *extra, **kwargs)
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_local.py", line 45, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_local.py", line 79, in run_file
    run(argv, addr, **kwargs)
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_local.py", line 140, in _run
    _pydevd.main()
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line1934, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line1283, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line1290, in _exec
Traceback (most recent call last):
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/liukai/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_execfile.py", line 25, in execfile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/liukai/_D/CornerNet/train.py", line 198, in <module>
Error in atexit._run_exitfuncs:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):

    train(training_dbs, validation_db, args.start_iter)
  File "/media/liukai/_D/CornerNet/train.py", line 139, in train
    training = pinned_training_queue.get(block=True)
  File "/home/liukai/anaconda3/lib/python3.7/queue.py", line 170, in get
    self.not_empty.wait()
  File "/home/liukai/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()

Exception ignored in: <function tqdm.__del__ at 0x7f5a57950048>
Traceback (most recent call last):
  File "/home/liukai/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "/home/liukai/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "/home/liukai/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/home/liukai/anaconda3/lib/python3.7/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/home/liukai/anaconda3/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread`

**Comment by sunyuanrui** [comment]
You should try python3.6, it can only running in python3.6.

**Comment by jiachen0212** [comment]
i meet the bug:
training start...
0%| | 0/500000 [00:00<?, ?it/s]Segmentation fault
emm.... what's the meaning of Segmentation fault ???
